--CREATE DATABSE 
CREATE DATABASE Librarydb;
GO

----USE DATABASE
USE Librarydb;
GO

---CREATE TABLE
-- CREATE AUTHORS TABLE
CREATE TABLE AUTHORS (
    AUTHORID INT PRIMARY KEY,
	NAME NVARCHAR(100) NOT NULL,
	COUNTRY NVARCHAR(50)
	);
	GO

-- CREATE BOOK TABLE
CREATE TABLE BOOK (
    BOOKID INT PRIMARY KEY,
	TITLE NVARCHAR(150) NOT NULL,
	GENRE NVARCHAR(50),
	AUTHORID INT FOREIGN KEY REFERENCES AUTHORS(AUTHORID),
	PUBLISHEDYEAR INT,
	ISBN NVARCHAR (20) UNIQUE
	);
	GO

-- CREATE MEMBERS TABLE
CREATE TABLE MEMBERS (
     MEMBERID INT PRIMARY KEY,
	 FULLNAME NVARCHAR(100),
	 EMAIL NVARCHAR(100) UNIQUE,
	 JOINDATE DATE DEFAULT GETDATE()
	 );
	 GO

-- CREATE LENDING TABLE
CREATE TABLE LENDING (
     LENDINGID INT PRIMARY KEY,
	 BOOKID INT FOREIGN KEY REFERENCES BOOK(BOOKID),
	 MEMBERID INT FOREIGN KEY REFERENCES MEMBERS(MEMBERID),
	 ISSUEDATE DATE NOT NULL,
	 RETURNDATE DATE
	 );
	 GO

/*-- ER DIAGRAM STRUCTURE 
ENTITIES :
1) AUTHORS
2) BOOKS
3) MEMBERS
4) LENDING

RELATIONSHIP :
1) ONE AUTHOR WRTITE MANY BOOKS (1:N)
2) ONE MEMBER BORROWS MANY BOOKS THROUGH LENDING (1:N)
3) ONE BOOK CAN BE LENT MANY TIMES (1:N) WITH LENDING)

